version: 0.0
os: linux
files:
  - source: /
    destination: /root
hooks:
  AfterInstall:
    - location: deploy/scripts/code_deploy.yaml
      timeout: 60
      runas: root
  # AfterInstall:
  #   - location: scripts/after_install.sh
  #     timeout: 300
  #     runas: root