version: 0.2
environment_variables:
  plaintext:
    ARTIFACT_FILE_NAME: ""
    ECR_URL: ""
phases:
  # install:
  #   runtime-versions:
  #       docker: 18
  pre_build:
    commands:
      - ECR_URL="${AccountId}.dkr.ecr.${Region}.amazonaws.com/${DevPrefix}-${AppName}-${Environment}-${Branch}"
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin "${ECR_URL}"
  build:
    commands:
      - TIME=$(date '+%F-%H%M')
      - echo "export TIME=$TIME" >> set_env.sh
      - printenv >> variables.sh
      - echo "export Region=${Region}"  >> set_env.sh
      - echo "export Environment=${Environment}"  >> set_env.sh
      - echo "export Branch=${Branch}" >> set_env.sh
      - echo "export AppName=${AppName}" >> set_env.sh
      - echo "export DevPrefix=${DevPrefix}"  >> set_env.sh
      - docker build -t --tag "${ECR_URL}":latest .
      - docker push  "${ECR_URL}":latest 
  # post_build:
  #   commands:
  #     - echo Build completed on `date`
  #     - echo Pushing the Docker image...
  #     - echo "${ECR_URL}"
  #     - docker push  "${ECR_URL}":latest  

artifacts:
  files:
    - appspec.yml
    - set_env.sh
    - deploy/scripts/code_deploy.yaml
    - variables.sh
    
