#!/bin/bash
source /root/set_env.sh
aws ecr get-login-password --region ${AccountId} | docker login --username AWS --password-stdin ${AccountId}.dkr.ecr.${Region}.amazonaws.com/${DevPrefix}-${AppName}-${Environment}-${Branch}