#!/bin/bash
source /root/set_env.sh
docker stop ${AppName}-${Environment}
docker system prune -a
aws ecr get-login-password --region ${Region} | docker login --username AWS --password-stdin ${AccountId}.dkr.ecr.${Region}.amazonaws.com/${DevPrefix}-${AppName}-${Environment}-${Branch}
docker run -d -it --name ${AppName}-${Environment} ${AccountId}.dkr.ecr.${Region}.amazonaws.com/${DevPrefix}-${AppName}-${Environment}-${Branch}:latest