name: Build, Upload and Deploy

on:
    push:
        branches:
            - CI/CD
    pull_request:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
        ECR_REPOSITORY: sheraz-test-repo-gateway-backend
        IMAGE_TAG: latest
      run: |
        ls
        # docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        # docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG



  Deploy:
    needs: [Build]
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - name: CodeDeploy Deployment
      id: deploy
      run: |
        aws s3 ls
        # aws deploy create-deployment \
        #   --application-name Git_Application \
        #   --deployment-group-name development_gropup \
        #   --deployment-config-name CodeDeployDefault.OneAtATime \
        #   --github-location repository=${{ github.repository }},commitId=${{ github.sha }}

